# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode 8.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="HPTest"
    - UPDATE_DOCS="false"
    
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=Example
script:
# - set -o pipefail && xcodebuild test -workspace Example/HPTest.xcworkspace -scheme HPTest-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
# Following extra lines added for automate cocoapod release 
# Late if need can follow https://fuller.li/posts/automated-cocoapods-releases-with-ci/ 

deploy:
  provider: releases
  api_key:
    secure: 00a6c9a63fe3668f7e029e8359cec86e6fad5773
    file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    tags: true
