language: objective-c
osx_image: xcode7.3
cache:
  bundler: true
  cocoapods: true
  directories:
    - build
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
after_success:
  - bin/travis_deploy
script:
  - bundle install --jobs=3 --retry=3
  - pod repo update && rake pod:install
  - bundle exec rake clean
  - bundle exec rake spec
