#!/bin/bash

# Step 1 to push recent code to github
# Step 2 check podspec validation
# Step 3 register trunk user by email
# Step 4 push code through podspec 


echo  Step 1 to push recent code to github 

git add .
git commit -m ”initial”
git push -u origin master



echo  Step 2 check podspec validation

pod lib lint HPTest.podspec

echo  Step 3 register trunk user by email

# pod trunk register anurag.d.sharma@capgemini.com ‘Anurag’ --description='macbook'

echo  Step 4 trunk push to podspec  


red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
echo "${red}red text ${green}green text${reset}"

# Pod trunk me

# pod trunk push HPTest.podspec


