#!/bin/bash
echo hello anurag 
git add .
git commit -m ”initial”
git push -u origin master

echo —————————Wait checking validation————————— 
pod lib lint HPTest.podspec
echo —————————Result Above————————— 

